version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rental-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rental_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
